### ISSUE TITLE
docfx: remove URL fragments from Python TOC

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-templates#19]
## Expected Behavior
The TOC entries should not have URL fragments (`/path/to/doc#url-fragment`). They mess up the TOC parsing.

## Actual Behavior
Entries include URL fragments:

```
    section:
    - title: Overview
      path: /python/docs/reference/texttospeech/latest/google.cloud.texttospeech_v1.services.text_to_speech.html#google_cloud_texttospeech_v1_services_text_to_speech
    - title: google.cloud.texttospeech_v1.services.text_to_speech.TextToSpeechAsyncClient
      path: /python/docs/reference/texttospeech/latest/google.cloud.texttospeech_v1.services.text_to_speech.TextToSpeechAsyncClient.html#google_cloud_texttospeech_v1_services_text_to_speech_TextToSpeechAsyncClient
    - title: google.cloud.texttospeech_v1.services.text_to_speech.TextToSpeechClient
      path: /python/docs/reference/texttospeech/latest/google.cloud.texttospeech_v1.services.text_to_speech.TextToSpeechClient.html#google_cloud_texttospeech_v1_services_text_to_speech_TextToSpeechClient
```

## Steps to Reproduce the Problem

1. Run the tests for this repo.
1. Look at `testdata/python-small/site/api/toc.html`.

cc @tmatsuo
