### ISSUE TITLE
docfx: deduplicate double Overview links

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-templates#20]
## Expected Behavior
There is only one Overview link in a TOC section.

## Actual Behavior
The Python TOC has two Overview links:
1. It includes a `path:` for each section, which leads to an automatic Overview link. This URL is sometimes incorrect.
1. It includes a dedicated Overview link, which looks like the right link.

```
  - title: google.cloud.texttospeech_v1.services.text_to_speech
    path: /python/docs/reference/texttospeech/latest/                # This is number 1. Not the right link.
    section:
    - title: Overview                                                # This is number 2.
      path: /python/docs/reference/texttospeech/latest/google.cloud.texttospeech_v1.services.text_to_speech.html#google_cloud_texttospeech_v1_services_text_to_speech
```

## Steps to Reproduce the Problem

1. Run the tests in this repo.
1. Look at `testdata/python-small/site/api/toc.html`.

-----------------

We should either:
* Update the Python generation to have the right link for the default one _and_ not include a dedicated Overview link.
* Update the template to detect this situation.

cc @tmatsuo @dzlier-gcp
