### ISSUE TITLE
bug: Return Types in DocFX escape HTML, making external/custom links impossible

### ISSUE THREAD

**Issue by bshaffer** [googleapis/doc-templates#424]
Return type linking in DocFX escapes HTML, which prevents us from manually writing the links, and breaks for things like union types, array types, and external links.

**Note:** This is only an issue for return types. The `type` fields for parameters do not function this way, and we are able to add HTML / `xref` to the YAML files, and it is rendered as expected in the resulting HTML.

**Example:**

If a return type has the value `\Google\Cloud\Vision\Annotation\Face[]|null`, we'd want to link only `\Google\Cloud\Vision\Annotation\Face` like so:

```yaml
  -
    uid: '\Google\Cloud\Vision\V1\BatchAnnotateFilesRequest::setParent()'
    type: method
    syntax:
      return:
        type:
          - <a href="https://somelink>\Google\Cloud\Vision\Annotation\Face</a>[]|null
```
However, this results in the string literal `<a href="https://somelink>\Google\Cloud\Vision\Annotation\Face</a>|null` showing up to the user in the resulting page as raw text, as the hyperlink is HTML-escaped by the DocFX html template:

```
&lt;a href=&quot;https://somelink&gt;GoogleCloudVisionAnnotationFace&lt;/a&gt;|null
```

**Expected Behavior**
What would be better for us is if we could add html and `xref` tags directly into the `return.type` field, and these are rendered as hyperlinks in the resulting HTML:

```yaml
      return:
        type:
          - <a href="https://somelink>\Google\Cloud\Vision\Annotation\Face</a>[]|null
```
And this would be rendered _unescaped_ into the resulting HTML as:
```
<a href="https://somelink>\Google\Cloud\Vision\Annotation\Face</a>[]|null
```

**Potential Workaround**
We could try a workaround using the `return.description` field:

```yaml
      return:
        type:
          - \Google\Cloud\Vision\Annotation\Face[]|null
        description:
          - An array of <xref uid="\Google\Cloud\Vision\Annotation\Face">\Google\Cloud\Vision\Annotation\Face</xref> or <code>null<code>
```
