### ISSUE TITLE
xref not linking in DoxFX YAML Summary

### ISSUE THREAD

**Issue by bshaffer** [googleapis/doc-templates#436]
_This could be Working As Designed, and I am just doing something wrong._

When generating DocFX YAML, we replace the following link for "attestors" in the PHPdoc class summary:

```php
namespace Google\Cloud\BinaryAuthorization\V1beta1;
/**
 * An [admission rule][google.cloud.binaryauthorization.v1beta1.AdmissionRule] specifies either that all container images
 * used in a pod creation request must be attested to by one or more
 * [attestors][google.cloud.binaryauthorization.v1beta1.Attestor]
 */
class AdmissionRule
```

With the following `xref` tag:

```yaml
items:
  -
    uid: \Google\Cloud\BinaryAuthorization\V1beta1\AdmissionRule
    summary: |
      An <xref uid="\Google\Cloud\Binaryauthorization\V1beta1\AdmissionRule">admission rule</xref> specifies either that all container images
      used in a pod creation request must be attested to by one or more
      <xref uid="\Google\Cloud\Binaryauthorization\V1beta1\Attestor">attestors</xref>
```

**However**, when this is rendered into HTML, we see the following instead

```html
<p>An <span class="xref">admission rule</span> specifies either that all container images
used in a pod creation request must be attested to by one or more
<span class="xref">attestors</span>, that all pod creations will be allowed, or that all
pod creations will be denied.</p>
```

I double checked all the references, and the "uid" matches for the DocFX yaml file `V1beta1.Attestor.yaml`:
```yaml
items:
  -
    uid: \Google\Cloud\BinaryAuthorization\V1beta1\Attestor
```

As well as the "uid" in our nested navigation item in `_toc.yaml`:

```
-
  uid: google-cloud-binary-authorization
  name: google/cloud-binary-authorization
  status: beta
  items:
        -
          name: Messages
          uid: 'messages:Google\Cloud\BinaryAuthorization\V1beta1'
          items:
            -
              uid: \Google\Cloud\BinaryAuthorization\V1beta1\Attestor
              name: Attestor
              status: beta
```

So, why is the `<xref>` HTML tag not being rendered correctly?
